### ISSUE TITLE
latest go image on DockerHub is missing go ...

### ISSUE THREAD

**Issue by elephantjim** [iron-io/dockers#12]
Say, something must be off in the build process.  The Dockerfile in dockers/go/go-1.5/Dockerfile seems just fine, but if I `docker pull iron/go:latest`, go isn't installed in the image.  One clue is https://hub.docker.com/r/iron/go/tags/ shows the image is only 4mb where the 1.4 image is 64mb.

Something's hinky.

**Comment by treeder** [comment]
Hey @elephantjim , use `iron/go:dev` for building and `iron/go` for running. Trying to be consistent with all our other images.

**Comment by elephantjim** [comment]
Ah, sorry.  I thought go was more like node, ruby, php, or python.  No interpreter.  Oops.

At the same time, why is the 1.4 tag so fat relative to the 1.5 tag if neither of them contain the go command for building?  Also, 1.5-dev is missing go, but dev has it.

Anywho, NBD.  Feel free to close this issue.

**Comment by treeder** [comment]
The 1.4 image has Go in it, we just added `go:dev` tag for 1.5 only.

**Comment by ches** [comment]
This surprised us too, build automation that was previously working with the `iron/go:1.5.1` tag started breaking on systems that pulled a different image version that is missing the `go` binary (I hope that changing the hash/content of tags with explicit versions will be avoided now that the change to consistent scheme is done…).

As @elephantjim says, the version-specific `-dev` tags appear to be missing `go`—I tried `1.5.1-dev` and it's the same. I assume that these are supposed to be images for building that are locked to particular Go versions. We want that, and we had it a few weeks ago.

@treeder could you perhaps re-open this ticket until these `x-dev` tags are fixed?

**Comment by treeder** [comment]
Ya, sorry guys, this scheme will stay for a while now, and we won't change containers that are already tagged and exist. 

And you're right, looks like the version dev tags aren't built properly. Fixing now...

**Comment by treeder** [comment]
Ok, should be fixed now: https://hub.docker.com/r/iron/go/tags/

**Comment by ches** [comment]
Thanks for the quick fix Travis!
