### ISSUE TITLE
Getting error: no such file or directory when running docker iron/cli image

### ISSUE THREAD

**Issue by lauraweindorf** [iron-io/dockers#14]
When I try to run the following command, I'm getting an error from docker saying it can't start the container, with additional "no such file or directory" error that I think is coming from the iron/cli image itself.

`docker run --rm  iron/cli --version`

![dockerironcli](https://cloud.githubusercontent.com/assets/436905/11609354/bfc64b04-9b52-11e5-90f6-7acf0ab4035a.png)

## Version Info
Windows 10
Docker 1.9.1
Oracle VirtualBox 5.0.11r104393
iron/cli docker image: (latest) 2b76d773706a

My docker VM was created using Kitematic and looks like it has a minimal set of commands. I'm not that familiar with the linux version, but it says `"MingGW64"`. 

I noticed in Kitematic the PATH has references to `sbin` which doesn't exist:

![kitematic](https://cloud.githubusercontent.com/assets/436905/11609392/f5e03280-9b53-11e5-90f8-e07ad2d52102.png)

I'm assuming the image is referencing a command that either isn't available in my MinGW64-version of linux or is in another location? Is there a workaround, like maybe modifying the PATH environment variable?

**Comment by rdallman** [comment]
hi @lauraweindorf , thanks for the report. uploaded version `0.0.22` which should fix the issue with `iron/cli` image

**Comment by rdallman** [comment]
please reopen if issues persist, thanks!

**Comment by lauraweindorf** [comment]
That worked! Thank you for such a quick fix @rdallman :-D
