### ISSUE TITLE
Oracle java images

### ISSUE THREAD

**Issue by Toilal** [iron-io/dockers#17]
It would be great to have oracle jre/jdk images. Is it planned ?

**Comment by treeder** [comment]
I think the Oracle JDK has some distribution issues (legal ones). 

Does OpenJDK not have what you need?

**Comment by Toilal** [comment]
I was sticked to Java 6 days where OpenJDK was really slow compared to Sun/Oracle implementation, but it seems it's really good with 7/8 now, so forget about that :)

**Comment by treeder** [comment]
:+1:

**Comment by typekpb** [comment]
well, I guess most people use for production stuff oracle java. any chance to deal with it? Would love to see 7 and 8 versions.

**Comment by typekpb** [comment]
never mind, found oracle image based on alpile linux elsewhere: https://github.com/frol/docker-alpine-oraclejdk8
