### ISSUE TITLE
Perl lang image

### ISSUE THREAD

**Issue by cjeanneret** [iron-io/dockers#19]
Hello,

Would be marvelous to get a Perl minimal image :).

Cheers,

C.

**Comment by LeoCBS** [comment]
Hi, i could make one perl image based on alpine and submit one PR..

what you think?

**Comment by cjeanneret** [comment]
I was going to investigate that way by the end of this week :). Thus, if you have something, that might be nice enough :smile:

**Comment by treeder** [comment]
Hey guys, PR's welcome.

**Comment by electricface** [comment]
perl 5.22.1

**Comment by treeder** [comment]
Done, can you guys try it out? iron/perl
