### ISSUE TITLE
Node v5 (for new NPM)

### ISSUE THREAD

**Issue by willrstern** [iron-io/dockers#21]
a node v5 version would be great. It includes NPM 3 which has some awesome improvements.

**Comment by treeder** [comment]
Need to wait for the Node 5 alpine package....

**Comment by Toilal** [comment]
As an alternative, here's an alpine based node container built from sources : https://github.com/mhart/alpine-node

**Comment by willrstern** [comment]
@Toilal That's actually the one I'm going with in the meantime.  Thanks!

**Comment by treeder** [comment]
I updated the iron/node images to use mhart's for node 5 for the time being. 

```sh
docker run --rm iron/node node -v
v5.5.0
```
