### ISSUE TITLE
C++ Support

### ISSUE THREAD

**Issue by mcraveiro** [iron-io/dockers#27]
Hi,

I have hit exactly this problem building images for c++ development. Would you guys consider images with clang/gcc and boost?

Keep up the great work!

Marco

**Comment by nikhilm** [comment]
Hi Marco,

"hit exactly this problem" which problem are you talking about? Generally we recommend that you create a Docker container that has a pre-compiled binary since that leads to a smaller image. What is your use case for having the compiler available in the image?

**Comment by treeder** [comment]
@nikhilm it's nice to have the `:dev` images with the build tools in them though. Like `iron/go:dev`. 

@mcraveiro been a while since I've done any c++, is Boost pretty common?

**Comment by mcraveiro** [comment]
@nikhilm @treeder yep, exactly right - I wanted to build a development image for C++ so I could use it on the project's CI. Using Ubuntu, the image is over 600 meg - not practical for a CI as there is no caching, etc. I then looked at the raw size of boost and clang and figured out the image should be less than 100 meg so there is a big differential here. As I was about to build my own images by compiling everything from scratch, I found iron.io.

@treeder  Boost is the foundational library for a very large set of C++ code so its pretty essential really.

**Comment by treeder** [comment]
Made a PR for this, review would be great.

**Comment by treeder** [comment]
Tested it and it works: https://github.com/iron-io/dockerworker/tree/master/gcc

Dev image size: [![](http://badge-imagelayers.iron.io/iron/gcc:dev.svg)](http://imagelayers.iron.io/?images=iron/gcc:dev 'Get your own badge on imagelayers.iron.io')

Run image size much smaller: [![](http://badge-imagelayers.iron.io/iron/gcc:latest.svg)](http://imagelayers.iron.io/?images=iron/gcc:latest 'Get your own badge on imagelayers.iron.io')
