### ISSUE TITLE
segmentation fault with a very simple web.py program on iron/python:2

### ISSUE THREAD

**Issue by markriggins** [iron-io/dockers#31]
Dockerfile ==================================

FROM iron/python:2

RUN apk add --update py-pip

COPY / /usr/app
WORKDIR /usr/app
RUN pip install -r requirements.txt
RUN python setup.py install

hello-python.py ======================
import web
import os

urls = (
    r'/hello', 'hello',
)

app = web.application(urls, globals())

class hello:  
    def GET(self, name):
        return 'Hello ' + os.environ.get('WORLD', 'world') + "!\n"

**Comment by markriggins** [comment]
requirements.txt:

        web.py

**Comment by treeder** [comment]
Doesn't work, please provide complete working example.

**Comment by Vanuan** [comment]
Fixed python source if that's an issue:

```python
import web
import os

urls = (r'/hello', 'hello',)

app = web.application(urls, globals())

class hello:
  def GET(self, name):
    return 'Hello ' + os.environ.get('WORLD', 'world') + "!\n"
```

**Comment by Vanuan** [comment]
requirements.txt is missing though
