### ISSUE TITLE
Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by ivpusic** [iron-io/dockers#32]
Getting this one for java 8 image when I access some https url from my java code.

Any ideas?

**Comment by treeder** [comment]
Can you post some example code to reproduce?

**Comment by ivpusic** [comment]
just access https from java. Do simple GET for example

**Comment by ligustah** [comment]
I encountered the same problem when trying to run Maven, which I manually installed into a node container. It's not really breaking anything for me, just happened to stumble upon this issue.

**Comment by treeder** [comment]
Need example code to reproduce.

**Comment by nikhilm** [comment]
@ivpusic The ca-certificates are installed on the alpine image. I tried hitting https://google.com with a basic Java client and that worked. What URL are you trying to reach? Are you changing any SSL params or using a non-default keystore?

**Comment by ivpusic** [comment]
Here is example code:

```Java
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ben' at '2/6/16 8:39 PM' with Gradle 2.10
 *
 * @author ben, @date 2/6/16 8:39 PM
 */
public final class Library {

    public final static void main(String[] args) throws UnirestException {

        System.out.println(Unirest.get("https://www.google.de").asString().getStatus());
    }
}
```

All default settings.

**Comment by nikhilm** [comment]
Thanks for the info Ivan. As I'm not a Java dev, I'm having trouble with
installing dependencies. How does one install Unirest in these Docker
images? Is there a simple maven command or something I can run in the same
docker container? Thanks.

**Comment by ivpusic** [comment]
you can build jar on your host machine, put it into your container and then run it with java -jar command

**Comment by BupycHuk** [comment]
@ivpusic try to use bupychuk/spring-batch

**Comment by rkononov** [comment]
@BupycHuk could you try to reproduce and fix this image?
Thanks.

**Comment by rkononov** [comment]
@nikhilm we'll handle this one

**Comment by BupycHuk** [comment]
@ivpusic we updated iron/java image. Could you try again?

**Comment by ivpusic** [comment]
works! thanks

**Comment by sukrit007** [comment]
running this issue with java-7 jdk. Here is a groovy snippet to reproduce: 
```
groovy:000> new URL('https://google.com').openConnection().inputStream.close()
ERROR javax.net.ssl.SSLException:
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

**Comment by treeder** [comment]
@sukrit007 can you ensure you've docker pulled the latest image?

**Comment by nikhilm** [comment]
I believe the Java 7 image was not updated.

**Comment by sukrit007** [comment]
Confirmed . I have latest from docker hub.

**Comment by treeder** [comment]
Oh, let me update the 1.7's.

**Comment by treeder** [comment]
@sukrit007 can you use the 1.8 image?

**Comment by sukrit007** [comment]
I am using Java8 image for other project and it works fine. My current
project had a hard dependency on java7.

On Tue, Mar 1, 2016 at 12:12 PM, Travis Reeder <notifications@github.com>
wrote:

> @sukrit007 <https://github.com/sukrit007> can you use the 1.8 image?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iron-io/dockers/issues/32#issuecomment-190857217>.
>



--

**Comment by treeder** [comment]
Rebuilding java 1.7 images now...

**Comment by treeder** [comment]
Can you pull 1.7 and try now @sukrit007

**Comment by sukrit007** [comment]
Still not working (same issue as before).  Confirmed, I have latest image : 
```
docker pull iron/java:1.7-dev 
1.7-dev: Pulling from iron/java
ee54741ab35b: Already exists 
424feef11a88: Already exists 
a1a3f5e45c1d: Already exists 
Digest: sha256:a47b3ebd5c983d2258bed690d9177068a63d17eaecaa04ef2e11597f1fedb5a6
Status: Image is up to date for iron/java:1.7-dev
```

**Comment by BupycHuk** [comment]
@sukrit007 could you try again?

**Comment by sukrit007** [comment]
Works now thanks !
