### ISSUE TITLE
Add git to the node:dev docker image

### ISSUE THREAD

**Issue by maxfrigge** [iron-io/dockers#35]
Unfortunately there are quite a few packages on npm that rely on github dependencies; on of which is this [super awesome iron.io client](https://github.com/assaf/ironium/blob/master/package.json#L17). Those packages can obviously only be used when git is installed. 

Would you consider adding git to `iron/node:dev` or is that against your "as slim as possible" policy?

**Comment by treeder** [comment]
Makes sense, the dev images aren't that strict, so they can be a bit bigger. 

Wasn't even aware of that super awesome Iron.io client. Thanks for sharing. 

Pushed new node:dev images, please try.

**Comment by maxfrigge** [comment]
Works like a charm! Cheers!

**Comment by treeder** [comment]
:metal:
