### ISSUE TITLE
SSL Certificates

### ISSUE THREAD

**Issue by davidgoate** [iron-io/dockers#39]
Is there something special required to get SSL certificates to work well in the java 1.8 base image?

My image was previously running on Oracle Hotspot JRE 8 in an Ubuntu based image and working ok.  Since switching my Dockerfile to `FROM iron/java:1.8` I have trouble connecting to HTTPS URL's within my application.

The precise error is:

```
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty; nested exception is javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

I initially suspected that perhaps some default certificates were missing, so I attempted the following:

```
RUN apk --update upgrade && \
    apk add ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/cache/apk/*
```

However I still have the same problem. 

I have played around inside the image and I did discover that the symlink `/usr/lib/jvm/java-1.8-openjdk/jre/lib/security/cacerts` pointed to a file `/etc/ssl/certs/java/cacerts` which did not exist. 

In order to attempt to remedy this I also executed:

```
RUN ln -s /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/java/cacerts
```

However the error is still the same.

What am I missing? Any help much appreciated.
Thanks.

**Comment by BupycHuk** [comment]
Hi @davidgoate 
we updated iron/java:1.8 image about hour ago. This error should be fixed. Could you rebuild your image?

**Comment by davidgoate** [comment]
@BupycHuk Hi, I just updated and tried again and unfortunately the issue is exactly the same.

For reference here is the image I'm using:

```
iron/java                   1.8                 404575c4665c
```

The MD5 sum of the cacerts file is:

```
/etc/ssl/certs/java $ md5sum cacerts 
a3812beee90ea2e956e7c84839825868  cacerts
```

Is this an issue with OpenJDK or with Alpine certificates?

**Comment by davidgoate** [comment]
@BupycHuk Sorry, false alarm. It actually appears to be working now. I think I was looking at a cached response in my browser. It appears to work just fine now. 

Thanks for the assistance.

**Comment by BupycHuk** [comment]
@davidgoate you are welcome!
