### ISSUE TITLE
Tag all images

### ISSUE THREAD

**Issue by treeder** [iron-io/dockers#4]
@freeman1988 please be sure tag all images with the version: https://hub.docker.com/r/iron/python/tags/

**Comment by freeman1988** [comment]
@treeder sorry, but seems i have no access to docker hub any more...
ps. it is python-2.7. maybe we should push python3 to python repo and delete python3 repo?

**Comment by treeder** [comment]
Probably just one python repo makes sense with tags?

**Comment by treeder** [comment]
Ya, going to merge everything into single language images. I got it from here.
