### ISSUE TITLE
Trouble with OpenRC/init (iron/scala)

### ISSUE THREAD

**Issue by gzoller** [iron-io/dockers#40]
I'm a bit confused where the openrc (rc-status, etc.) comes from.  The 'latest' alpine doesn't have it but I don't see it in the Dockerfile tree here in iron-io.  Strange.

In any event, I build a Docker file off iron/scala:

FROM iron/scala
USER root
ENTRYPOINT ["/sbin/init","/bin/bash"]

Eventually I'm trying to start OpenRC's init to launch some processes I want running.  This is the output I see (stock...I haven't added my processes yet to /etc/init.d):

docker run -it foo/bar

   OpenRC 0.15.1.88bc7e0 is starting up Linux 4.0.9-boot2docker (x86_64)
- /proc is already mounted
- Mounting /run ...
  mount: permission denied (are you root?)
- Unable to mount tmpfs on /run.
- Can't continue.
- Caching service dependencies ...                                                                                                                         [ ok ]
  can't open /dev/tty1: No such file or directory
  can't open /dev/tty2: No such file or directory
  can't open /dev/tty3: No such file or directory
  ... (just keeps coughing these out)

**Comment by noqcks** [comment]
This is an issue with basically any init system in docker that needs to run as PID1. 

There's a [closed issue thread on the official `docker-alpine` repo](https://github.com/gliderlabs/docker-alpine/issues/42) that will give you some context.
