### ISSUE TITLE
gem install json-1.8.3 failed on ruby 2.2.0

### ISSUE THREAD

**Issue by ducle** [iron-io/dockers#54]
`Fetching: json-1.8.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20160623-7-1yb7ssr.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /usr/lib/ruby/gems/2.2.0/gems/json-1.8.3 for inspection.
Results logged to /usr/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0/json-1.8.3/gem_make.out`

How can we fix this?

**Comment by treeder** [comment]
Are you using `iron/ruby:dev` to build?

**Comment by ducle** [comment]
no, I used iron/ruby. 
But I fixed it with 

apk add gcc make libc-dev ruby-dev ruby-rdoc ruby-irb
