### ISSUE TITLE
Update iron/node image

### ISSUE THREAD

**Issue by ccirello** [iron-io/dockers#56]
```
It's pretty old now: https://github.com/iron-io/dockers/tree/master/node

And maybe some of the other images in there as well. Perhaps make a top level rebuild all images script that builds and pushes everything. 
```

See https://github.com/iron-io/functions/issues/284

**Comment by nimajalali** [comment]
Tried to run this myself and the images build but I can't push to dockerhub (which in hindsight makes sense)

Any chance someone at Iron.io can run this?

**Comment by drpebcak** [comment]
+1 it would be nice to have boron in there to use.
