### ISSUE TITLE
Regarding Iron.io Docker Images - Microcontainers

### ISSUE THREAD

**Issue by honeyankit** [iron-io/dockers#60]
I have one question related to building micro size docker images ?

In the below buider.rb file (vtag function) why you are creating three tags for a image VERSION_ID say 3.5.0  ?

https://github.com/iron-io/dockers/blob/master/utils/builder.rb

Warm Regards,
Ankit

**Comment by treeder** [comment]
It creates a `3.5.0` tag, a `3.5` tag and a `3` tag.

**Comment by honeyankit** [comment]
My question is all that if all the  three tags 3.5.0, 3.5 and 3 from same image. If yes then what is the significance of creating 3 different tags?

**Comment by nikhilm** [comment]
When 3.5.1 is released, 3.5 and 3 will be changed to point to 3.5.1. This
way users of 3 and 3.5 automatically get the latest release, but users who
explicitly want 3.5.0 can continue to use it.

Best,
Nikhil
