### ISSUE TITLE
iron/go:dev - dep doesn't work

### ISSUE THREAD

**Issue by x1unix** [iron-io/dockers#67]
### Issue
`dep` dependency manager for Go doesn't work on containers based on `iron/go:dev`

**Dockerfile**

```
FROM iron/go:dev

RUN apk update; apk add git
RUN go get -u github.com/golang/dep/cmd/dep

ENTRYPOINT /bin/sh
```

**In container (bash):**
```
$ dep
dep: command not found
```

**P.S** - everything works with the same steps using `golang:1.9.2-alpine` image

**Comment by vasilev** [comment]
Thank you for report. Digging into it.

**Comment by vasilev** [comment]
Could not reproduce your issue.
Tried:
```
cat << EOF > Dockerfile-issue-67
FROM iron/go:dev

RUN apk update; apk add git
RUN go get -u github.com/golang/dep/cmd/dep

ENTRYPOINT /bin/sh
EOF

docker build -f Dockerfile-issue-67 -t iron/go:issue-67 .

docker run --rm --entrypoint=dep  iron/go:issue-67 version
```
Last command output:
```
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : go1.9.3
 go compiler : gc
 platform    : linux/amd64
```
@x1unix could you please provide a detailed instructions to reproduce ?

**Comment by x1unix** [comment]
@vasilev, here are my steps:
```
$ docker build -t foobar .
$ docker run -it --rm foobar
```

On Docker For Windows everything runs well.
Issue appears on macOS High Sierra

**Comment by c0ze** [comment]
@x1unix 

I can confirm it works as expected also on High Sierra. (ie dep gets installed and is present.).

**Comment by x1unix** [comment]
@c0ze, it's strange but today everything is working. Maybe it's my own Docker's issue. Closing issue

**Comment by vasilev** [comment]
OK, let us know if you have any issues.
BTW, `git` is already [bundled](https://github.com/iron-io/dockers/blob/master/go/dev/Dockerfile#L3) into `iron/go:dev` image.
